import { Product } from '@/types/product';

export const mockProducts: Product[] = [
  // CAMERAS (25 products)
  {
    id: '1',
    name: 'Canon EOS R5',
    slug: 'canon-eos-r5',
    description: 'Professional full-frame mirrorless camera with 45MP sensor and 8K video recording capabilities. Perfect for professional photographers and videographers.',
    price: 389900,
    originalPrice: 429900,
    images: [
      '/images/cameras/canon-eos-r5.jpg',
      '/placeholder.svg?height=800&width=800&text=Canon+EOS+R5+Back',
      '/placeholder.svg?height=800&width=800&text=Canon+EOS+R5+Side',
      '/placeholder.svg?height=800&width=800&text=Canon+EOS+R5+Top'
    ],
    category: 'cameras',
    subcategory: 'mirrorless',
    brand: 'Canon',
    rating: 4.8,
    reviewCount: 234,
    inStock: true,
    badges: ['hot'],
    specs: {
      sensor: 'Full Frame 45MP',
      video: '8K RAW',
      iso: '100-51200',
      mount: 'RF Mount',
    },
    variants: [
      { id: 'v1', name: 'Body Only', price: 389900, inventory: 10 },
      { id: 'v2', name: 'With 24-105mm Kit', price: 479900, inventory: 5 },
      { id: 'v3', name: 'With 24-70mm Kit', price: 519900, inventory: 8 }
    ],
  },
  {
    id: '2',
    name: 'Sony A7 IV',
    slug: 'sony-a7-iv',
    description: 'Versatile full-frame mirrorless camera perfect for hybrid creators. 33MP sensor with advanced autofocus and 4K60 video.',
    price: 249900,
    images: [
      '/images/cameras/sony-a7-iv.jpg',
      '/placeholder.svg?height=800&width=800&text=Sony+A7+IV+Back',
      '/placeholder.svg?height=800&width=800&text=Sony+A7+IV+Side',
      '/placeholder.svg?height=800&width=800&text=Sony+A7+IV+Top'
    ],
    category: 'cameras',
    subcategory: 'mirrorless',
    brand: 'Sony',
    rating: 4.7,
    reviewCount: 456,
    inStock: true,
    badges: ['new'],
    specs: {
      sensor: 'Full Frame 33MP',
      video: '4K60',
      iso: '100-51200',
      mount: 'E Mount',
    },
    variants: [
      { id: 'v1', name: 'Body Only', price: 249900, inventory: 15 },
      { id: 'v2', name: 'With 28-70mm Kit', price: 299900, inventory: 12 }
    ],
  },
  {
    id: '3',
    name: 'Nikon Z9',
    slug: 'nikon-z9',
    description: 'Flagship mirrorless camera with 8K video and advanced autofocus. The ultimate tool for professional photographers.',
    price: 549900,
    images: [
      '/placeholder.svg?height=800&width=800&text=Nikon+Z9+Front',
      '/placeholder.svg?height=800&width=800&text=Nikon+Z9+Back',
      '/placeholder.svg?height=800&width=800&text=Nikon+Z9+Side',
      '/placeholder.svg?height=800&width=800&text=Nikon+Z9+Top'
    ],
    category: 'camera',
    brand: 'Nikon',
    rating: 4.9,
    reviewCount: 189,
    inStock: true,
    badges: ['hot', 'new'],
    specs: {
      sensor: 'Full Frame 45.7MP',
      video: '8K30',
      iso: '64-25600',
      mount: 'Z Mount',
    },
    variants: [
      { id: 'v1', name: 'Body Only', price: 549900, inventory: 8 }
    ],
  },
  {
    id: '4',
    name: 'Fujifilm X-T5',
    slug: 'fujifilm-xt5',
    description: 'Retro-styled APS-C camera with 40MP sensor and film simulations. Classic design meets modern technology.',
    price: 169900,
    originalPrice: 189900,
    images: [
      '/placeholder.svg?height=800&width=800&text=Fujifilm+X-T5+Front',
      '/placeholder.svg?height=800&width=800&text=Fujifilm+X-T5+Back'
    ],
    category: 'camera',
    brand: 'Fujifilm',
    rating: 4.6,
    reviewCount: 321,
    inStock: true,
    lowStock: true,
    badges: ['sale'],
    specs: {
      sensor: 'APS-C 40MP',
      video: '6.2K',
      iso: '125-12800',
      mount: 'X Mount',
    },
    variants: [
      { id: 'v1', name: 'Body Only', price: 169900, inventory: 3 },
      { id: 'v2', name: 'With 18-55mm Kit', price: 199900, inventory: 2 }
    ],
  },
  {
    id: '5',
    name: 'Canon RF 24-70mm f/2.8L',
    slug: 'canon-rf-24-70mm',
    description: 'Professional standard zoom lens with constant f/2.8 aperture for stunning image quality',
    price: 229900,
    images: ['/placeholder.svg?height=800&width=800&text=Canon+24-70mm'],
    category: 'lens',
    brand: 'Canon',
    rating: 4.8,
    reviewCount: 167,
    inStock: true,
    specs: {
      aperture: 'f/2.8',
      range: '24-70mm',
      mount: 'RF Mount',
      weight: '900g',
    },
  },
  {
    id: '6',
    name: 'Sony FE 70-200mm f/2.8 GM OSS II',
    slug: 'sony-fe-70-200mm',
    description: 'Telephoto zoom lens with exceptional sharpness and bokeh for portraits and sports',
    price: 279900,
    images: ['/placeholder.svg?height=800&width=800&text=Sony+70-200mm'],
    category: 'lens',
    brand: 'Sony',
    rating: 4.9,
    reviewCount: 234,
    inStock: true,
    badges: ['new'],
    specs: {
      aperture: 'f/2.8',
      range: '70-200mm',
      mount: 'E Mount',
      weight: '1045g',
    },
  },
  {
    id: '7',
    name: 'Peak Design Everyday Backpack 30L',
    slug: 'peak-design-backpack',
    description: 'Premium camera backpack with customizable dividers and weatherproof construction',
    price: 29990,
    images: ['/placeholder.svg?height=800&width=800&text=Peak+Design+Backpack'],
    category: 'accessory',
    brand: 'Peak Design',
    rating: 4.7,
    reviewCount: 892,
    inStock: true,
    specs: {
      capacity: '30L',
      material: 'Weatherproof Canvas',
      weight: '1.8kg',
      dimensions: '52×30×23cm',
    },
  },
  {
    id: '8',
    name: 'DJI RS 3 Pro Gimbal',
    slug: 'dji-rs3-pro',
    description: 'Professional 3-axis gimbal stabilizer for cinema cameras with automated features',
    price: 86900,
    images: ['/placeholder.svg?height=800&width=800&text=DJI+RS3+Pro'],
    category: 'accessory',
    brand: 'DJI',
    rating: 4.6,
    reviewCount: 145,
    inStock: true,
    badges: ['hot'],
    specs: {
      payload: '4.5kg',
      battery: '12 hours',
      stabilization: '3-axis',
      weight: '1.3kg',
    },
  },
  {
    id: '9',
    name: 'Panasonic Lumix S5 II',
    slug: 'panasonic-lumix-s5-ii',
    description: 'Hybrid full-frame camera with phase-detection autofocus and excellent video features',
    price: 199900,
    images: ['/placeholder.svg?height=800&width=800&text=Panasonic+S5+II'],
    category: 'camera',
    brand: 'Panasonic',
    rating: 4.7,
    reviewCount: 178,
    inStock: true,
    badges: ['new'],
    specs: {
      sensor: 'Full Frame 24MP',
      video: '6K',
      iso: '100-51200',
      mount: 'L Mount',
    },
    variants: [
      { id: 'v1', name: 'Body Only', price: 199900, inventory: 12 }
    ],
  },
  {
    id: '10',
    name: 'Olympus OM-1',
    slug: 'olympus-om-1',
    description: 'Flagship Micro Four Thirds camera with computational photography features',
    price: 219900,
    images: ['/placeholder.svg?height=800&width=800&text=Olympus+OM-1'],
    category: 'camera',
    brand: 'Olympus',
    rating: 4.5,
    reviewCount: 156,
    inStock: true,
    specs: {
      sensor: 'MFT 20MP',
      video: '4K60',
      iso: '200-25600',
      mount: 'MFT Mount',
    },
  },
  {
    id: '11',
    name: 'Leica Q3',
    slug: 'leica-q3',
    description: 'Premium fixed-lens full-frame camera with legendary Leica image quality',
    price: 549900,
    images: ['/placeholder.svg?height=800&width=800&text=Leica+Q3'],
    category: 'camera',
    brand: 'Leica',
    rating: 4.9,
    reviewCount: 89,
    inStock: true,
    badges: ['hot'],
    specs: {
      sensor: 'Full Frame 60MP',
      video: '8K',
      iso: '50-100000',
      mount: 'Fixed 28mm f/1.7',
    },
  },
  {
    id: '12',
    name: 'Nikon Z fc',
    slug: 'nikon-z-fc',
    description: 'Retro-styled APS-C mirrorless camera with modern features and classic design',
    price: 99900,
    images: ['/placeholder.svg?height=800&width=800&text=Nikon+Z+fc'],
    category: 'camera',
    brand: 'Nikon',
    rating: 4.4,
    reviewCount: 267,
    inStock: true,
    badges: ['sale'],
    specs: {
      sensor: 'APS-C 20.9MP',
      video: '4K30',
      iso: '100-51200',
      mount: 'Z Mount',
    },
  },
  {
    id: '13',
    name: 'Sony A7R V',
    slug: 'sony-a7r-v',
    description: 'Ultra-high resolution full-frame camera with AI-powered autofocus',
    price: 399900,
    images: ['/placeholder.svg?height=800&width=800&text=Sony+A7R+V'],
    category: 'camera',
    brand: 'Sony',
    rating: 4.8,
    reviewCount: 143,
    inStock: true,
    badges: ['new'],
    specs: {
      sensor: 'Full Frame 61MP',
      video: '8K',
      iso: '100-32000',
      mount: 'E Mount',
    },
  },
  {
    id: '14',
    name: 'Canon EOS R6 Mark II',
    slug: 'canon-eos-r6-ii',
    description: 'Fast and versatile full-frame camera perfect for action and wildlife',
    price: 269900,
    images: ['/placeholder.svg?height=800&width=800&text=Canon+R6+II'],
    category: 'camera',
    brand: 'Canon',
    rating: 4.7,
    reviewCount: 198,
    inStock: true,
    specs: {
      sensor: 'Full Frame 24MP',
      video: '4K60',
      iso: '100-102400',
      mount: 'RF Mount',
    },
  },
  {
    id: '15',
    name: 'Fujifilm X-H2S',
    slug: 'fujifilm-x-h2s',
    description: 'Flagship APS-C camera with stacked sensor for ultimate speed',
    price: 249900,
    images: ['/placeholder.svg?height=800&width=800&text=Fujifilm+X-H2S'],
    category: 'camera',
    brand: 'Fujifilm',
    rating: 4.8,
    reviewCount: 176,
    inStock: true,
    badges: ['hot'],
    specs: {
      sensor: 'APS-C 26MP',
      video: '6.2K',
      iso: '160-12800',
      mount: 'X Mount',
    },
  },
  {
    id: '16',
    name: 'Nikon Z 24-70mm f/2.8 S',
    slug: 'nikon-z-24-70mm',
    description: 'Professional standard zoom with exceptional sharpness across the frame',
    price: 239900,
    images: ['/placeholder.svg?height=800&width=800&text=Nikon+24-70mm'],
    category: 'lens',
    brand: 'Nikon',
    rating: 4.9,
    reviewCount: 234,
    inStock: true,
    specs: {
      aperture: 'f/2.8',
      range: '24-70mm',
      mount: 'Z Mount',
      weight: '805g',
    },
  },
  {
    id: '17',
    name: 'Sigma 85mm f/1.4 DG DN Art',
    slug: 'sigma-85mm-art',
    description: 'Premium portrait prime lens with stunning bokeh and sharpness',
    price: 119900,
    images: ['/placeholder.svg?height=800&width=800&text=Sigma+85mm'],
    category: 'lens',
    brand: 'Sigma',
    rating: 4.8,
    reviewCount: 312,
    inStock: true,
    badges: ['hot'],
    specs: {
      aperture: 'f/1.4',
      range: '85mm',
      mount: 'E/L/RF Mount',
      weight: '630g',
    },
  },
  {
    id: '18',
    name: 'Tamron 28-75mm f/2.8 Di III',
    slug: 'tamron-28-75mm',
    description: 'Compact and lightweight standard zoom with great value',
    price: 89900,
    images: ['/placeholder.svg?height=800&width=800&text=Tamron+28-75mm'],
    category: 'lens',
    brand: 'Tamron',
    rating: 4.6,
    reviewCount: 445,
    inStock: true,
    specs: {
      aperture: 'f/2.8',
      range: '28-75mm',
      mount: 'E Mount',
      weight: '550g',
    },
  },
  {
    id: '19',
    name: 'Manfrotto 055 Carbon Fiber Tripod',
    slug: 'manfrotto-055-tripod',
    description: 'Professional carbon fiber tripod for stable shooting in any condition',
    price: 34990,
    images: ['/placeholder.svg?height=800&width=800&text=Manfrotto+Tripod'],
    category: 'accessory',
    brand: 'Manfrotto',
    rating: 4.7,
    reviewCount: 567,
    inStock: true,
    specs: {
      material: 'Carbon Fiber',
      height: '170cm',
      load: '9kg',
      weight: '1.8kg',
    },
  },
  {
    id: '20',
    name: 'SanDisk Extreme PRO CFexpress',
    slug: 'sandisk-cfexpress',
    description: 'Ultra-fast memory card for 8K video and high-speed shooting',
    price: 24990,
    images: ['/placeholder.svg?height=800&width=800&text=SanDisk+Card'],
    category: 'accessory',
    brand: 'SanDisk',
    rating: 4.8,
    reviewCount: 789,
    inStock: true,
    badges: ['new'],
    specs: {
      capacity: '256GB',
      speed: '1700MB/s',
      type: 'CFexpress Type B',
      warranty: 'Lifetime',
    },
  },
  // Additional 40 products (21-60)
  {
    id: '21',
    name: 'Canon EOS R7',
    slug: 'canon-eos-r7',
    description: 'High-speed APS-C camera with bird and animal detection AF',
    price: 149900,
    originalPrice: 169900,
    images: ['/placeholder.svg?height=800&width=800&text=Canon+R7'],
    category: 'camera',
    brand: 'Canon',
    rating: 4.6,
    reviewCount: 234,
    inStock: true,
    badges: ['sale'],
    specs: { sensor: 'APS-C 32.5MP', video: '4K60', iso: '100-32000', mount: 'RF Mount' },
  },
  {
    id: '22',
    name: 'Sony ZV-E10',
    slug: 'sony-zv-e10',
    description: 'Vlogging camera with advanced audio and video features',
    price: 69900,
    images: ['/placeholder.svg?height=800&width=800&text=Sony+ZV-E10'],
    category: 'camera',
    brand: 'Sony',
    rating: 4.5,
    reviewCount: 567,
    inStock: true,
    badges: ['hot'],
    specs: { sensor: 'APS-C 24MP', video: '4K30', iso: '100-32000', mount: 'E Mount' },
  },
  {
    id: '23',
    name: 'Nikon Z6 III',
    slug: 'nikon-z6-iii',
    description: 'Versatile full-frame camera with partially stacked sensor',
    price: 279900,
    images: ['/placeholder.svg?height=800&width=800&text=Nikon+Z6+III'],
    category: 'camera',
    brand: 'Nikon',
    rating: 4.7,
    reviewCount: 187,
    inStock: true,
    badges: ['new'],
    specs: { sensor: 'Full Frame 24.5MP', video: '6K', iso: '100-64000', mount: 'Z Mount' },
  },
  {
    id: '24',
    name: 'Fujifilm X-S20',
    slug: 'fujifilm-xs20',
    description: 'Compact powerhouse with in-body stabilization',
    price: 134900,
    images: ['/placeholder.svg?height=800&width=800&text=Fuji+XS20'],
    category: 'camera',
    brand: 'Fujifilm',
    rating: 4.6,
    reviewCount: 298,
    inStock: true,
    specs: { sensor: 'APS-C 26MP', video: '6.2K', iso: '160-12800', mount: 'X Mount' },
  },
  {
    id: '25',
    name: 'Canon EOS R8',
    slug: 'canon-eos-r8',
    description: 'Compact and affordable full-frame option',
    price: 149900,
    images: ['/placeholder.svg?height=800&width=800&text=Canon+R8'],
    category: 'camera',
    brand: 'Canon',
    rating: 4.5,
    reviewCount: 223,
    inStock: true,
    specs: { sensor: 'Full Frame 24MP', video: '4K60', iso: '100-102400', mount: 'RF Mount' },
  },
  {
    id: '26',
    name: 'Sony A6700',
    slug: 'sony-a6700',
    description: 'Advanced APS-C with AI autofocus',
    price: 139900,
    images: ['/placeholder.svg?height=800&width=800&text=Sony+A6700'],
    category: 'camera',
    brand: 'Sony',
    rating: 4.7,
    reviewCount: 334,
    inStock: true,
    badges: ['new'],
    specs: { sensor: 'APS-C 26MP', video: '4K60', iso: '100-32000', mount: 'E Mount' },
  },
  {
    id: '27',
    name: 'Panasonic GH6',
    slug: 'panasonic-gh6',
    description: 'Ultimate video-centric Micro Four Thirds camera',
    price: 219900,
    images: ['/placeholder.svg?height=800&width=800&text=Panasonic+GH6'],
    category: 'camera',
    brand: 'Panasonic',
    rating: 4.8,
    reviewCount: 176,
    inStock: true,
    badges: ['hot'],
    specs: { sensor: 'MFT 25MP', video: '5.7K60', iso: '100-25600', mount: 'MFT Mount' },
  },
  {
    id: '28',
    name: 'Nikon Z5',
    slug: 'nikon-z5',
    description: 'Entry-level full-frame with dual card slots',
    price: 129900,
    images: ['/placeholder.svg?height=800&width=800&text=Nikon+Z5'],
    category: 'camera',
    brand: 'Nikon',
    rating: 4.4,
    reviewCount: 445,
    inStock: true,
    specs: { sensor: 'Full Frame 24MP', video: '4K30', iso: '100-51200', mount: 'Z Mount' },
  },
  {
    id: '29',
    name: 'Canon EOS R50',
    slug: 'canon-eos-r50',
    description: 'Compact beginner-friendly mirrorless camera',
    price: 69900,
    images: ['/placeholder.svg?height=800&width=800&text=Canon+R50'],
    category: 'camera',
    brand: 'Canon',
    rating: 4.3,
    reviewCount: 567,
    inStock: true,
    badges: ['sale'],
    specs: { sensor: 'APS-C 24MP', video: '4K30', iso: '100-32000', mount: 'RF-S Mount' },
  },
  {
    id: '30',
    name: 'Sony A7C II',
    slug: 'sony-a7c-ii',
    description: 'Compact full-frame with AI processor',
    price: 219900,
    images: ['/placeholder.svg?height=800&width=800&text=Sony+A7C+II'],
    category: 'camera',
    brand: 'Sony',
    rating: 4.6,
    reviewCount: 198,
    inStock: true,
    badges: ['new'],
    specs: { sensor: 'Full Frame 33MP', video: '4K60', iso: '100-51200', mount: 'E Mount' },
  },
  {
    id: '31',
    name: 'Canon RF 50mm f/1.8 STM',
    slug: 'canon-rf-50mm',
    description: 'Affordable and sharp nifty fifty prime lens',
    price: 24900,
    images: ['/placeholder.svg?height=800&width=800&text=Canon+50mm'],
    category: 'lens',
    brand: 'Canon',
    rating: 4.7,
    reviewCount: 789,
    inStock: true,
    specs: { aperture: 'f/1.8', range: '50mm', mount: 'RF Mount', weight: '160g' },
  },
  {
    id: '32',
    name: 'Sony FE 35mm f/1.4 GM',
    slug: 'sony-fe-35mm',
    description: 'Premium wide-angle prime with stunning bokeh',
    price: 149900,
    images: ['/placeholder.svg?height=800&width=800&text=Sony+35mm'],
    category: 'lens',
    brand: 'Sony',
    rating: 4.9,
    reviewCount: 267,
    inStock: true,
    badges: ['new'],
    specs: { aperture: 'f/1.4', range: '35mm', mount: 'E Mount', weight: '524g' },
  },
  {
    id: '33',
    name: 'Nikon Z 14-30mm f/4 S',
    slug: 'nikon-z-14-30mm',
    description: 'Ultra-wide zoom perfect for landscapes',
    price: 139900,
    images: ['/placeholder.svg?height=800&width=800&text=Nikon+14-30mm'],
    category: 'lens',
    brand: 'Nikon',
    rating: 4.7,
    reviewCount: 198,
    inStock: true,
    specs: { aperture: 'f/4', range: '14-30mm', mount: 'Z Mount', weight: '485g' },
  },
  {
    id: '34',
    name: 'Fujifilm XF 56mm f/1.2 R WR',
    slug: 'fujifilm-xf-56mm',
    description: 'Fast portrait prime with weather sealing',
    price: 99900,
    images: ['/placeholder.svg?height=800&width=800&text=Fuji+56mm'],
    category: 'lens',
    brand: 'Fujifilm',
    rating: 4.8,
    reviewCount: 334,
    inStock: true,
    badges: ['hot'],
    specs: { aperture: 'f/1.2', range: '56mm', mount: 'X Mount', weight: '445g' },
  },
  {
    id: '35',
    name: 'Canon RF 70-200mm f/4L IS USM',
    slug: 'canon-rf-70-200mm',
    description: 'Compact telephoto with excellent stabilization',
    price: 169900,
    images: ['/placeholder.svg?height=800&width=800&text=Canon+70-200mm'],
    category: 'lens',
    brand: 'Canon',
    rating: 4.7,
    reviewCount: 223,
    inStock: true,
    specs: { aperture: 'f/4', range: '70-200mm', mount: 'RF Mount', weight: '695g' },
  },
  {
    id: '36',
    name: 'Sony FE 24mm f/1.4 GM',
    slug: 'sony-fe-24mm',
    description: 'Premium wide-angle prime for astrophotography',
    price: 149900,
    images: ['/placeholder.svg?height=800&width=800&text=Sony+24mm'],
    category: 'lens',
    brand: 'Sony',
    rating: 4.9,
    reviewCount: 187,
    inStock: true,
    specs: { aperture: 'f/1.4', range: '24mm', mount: 'E Mount', weight: '445g' },
  },
  {
    id: '37',
    name: 'Tamron 70-300mm f/4.5-6.3',
    slug: 'tamron-70-300mm',
    description: 'Affordable telephoto zoom for wildlife',
    price: 59900,
    images: ['/placeholder.svg?height=800&width=800&text=Tamron+70-300mm'],
    category: 'lens',
    brand: 'Tamron',
    rating: 4.5,
    reviewCount: 445,
    inStock: true,
    badges: ['sale'],
    specs: { aperture: 'f/4.5-6.3', range: '70-300mm', mount: 'E/Z Mount', weight: '545g' },
  },
  {
    id: '38',
    name: 'Nikon Z 85mm f/1.8 S',
    slug: 'nikon-z-85mm',
    description: 'Lightweight portrait prime with smooth bokeh',
    price: 79900,
    images: ['/placeholder.svg?height=800&width=800&text=Nikon+85mm'],
    category: 'lens',
    brand: 'Nikon',
    rating: 4.8,
    reviewCount: 298,
    inStock: true,
    specs: { aperture: 'f/1.8', range: '85mm', mount: 'Z Mount', weight: '470g' },
  },
  {
    id: '39',
    name: 'Sigma 150-600mm f/5-6.3 DG DN',
    slug: 'sigma-150-600mm',
    description: 'Super-telephoto for sports and wildlife',
    price: 149900,
    images: ['/placeholder.svg?height=800&width=800&text=Sigma+150-600mm'],
    category: 'lens',
    brand: 'Sigma',
    rating: 4.7,
    reviewCount: 234,
    inStock: true,
    badges: ['hot'],
    specs: { aperture: 'f/5-6.3', range: '150-600mm', mount: 'E/L Mount', weight: '1830g' },
  },
  {
    id: '40',
    name: 'Canon RF 100-500mm f/4.5-7.1L',
    slug: 'canon-rf-100-500mm',
    description: 'Versatile super-telephoto zoom',
    price: 279900,
    images: ['/placeholder.svg?height=800&width=800&text=Canon+100-500mm'],
    category: 'lens',
    brand: 'Canon',
    rating: 4.8,
    reviewCount: 167,
    inStock: true,
    badges: ['new'],
    specs: { aperture: 'f/4.5-7.1', range: '100-500mm', mount: 'RF Mount', weight: '1370g' },
  },
  {
    id: '41',
    name: 'Sony FE 200-600mm f/5.6-6.3 G OSS',
    slug: 'sony-fe-200-600mm',
    description: 'Professional super-telephoto for ultimate reach',
    price: 199900,
    images: ['/placeholder.svg?height=800&width=800&text=Sony+200-600mm'],
    category: 'lens',
    brand: 'Sony',
    rating: 4.9,
    reviewCount: 143,
    inStock: true,
    badges: ['hot'],
    specs: { aperture: 'f/5.6-6.3', range: '200-600mm', mount: 'E Mount', weight: '2115g' },
  },
  {
    id: '42',
    name: 'Fujifilm XF 16-80mm f/4',
    slug: 'fujifilm-xf-16-80mm',
    description: 'All-in-one travel zoom with weather sealing',
    price: 79900,
    images: ['/placeholder.svg?height=800&width=800&text=Fuji+16-80mm'],
    category: 'lens',
    brand: 'Fujifilm',
    rating: 4.6,
    reviewCount: 387,
    inStock: true,
    specs: { aperture: 'f/4', range: '16-80mm', mount: 'X Mount', weight: '440g' },
  },
  {
    id: '43',
    name: 'Tamron 17-28mm f/2.8 Di III',
    slug: 'tamron-17-28mm',
    description: 'Compact ultra-wide zoom with constant aperture',
    price: 89900,
    images: ['/placeholder.svg?height=800&width=800&text=Tamron+17-28mm'],
    category: 'lens',
    brand: 'Tamron',
    rating: 4.7,
    reviewCount: 456,
    inStock: true,
    specs: { aperture: 'f/2.8', range: '17-28mm', mount: 'E Mount', weight: '420g' },
  },
  {
    id: '44',
    name: 'Nikon Z 100-400mm f/4.5-5.6 VR S',
    slug: 'nikon-z-100-400mm',
    description: 'Lightweight super-telephoto with excellent VR',
    price: 269900,
    images: ['/placeholder.svg?height=800&width=800&text=Nikon+100-400mm'],
    category: 'lens',
    brand: 'Nikon',
    rating: 4.8,
    reviewCount: 134,
    inStock: true,
    badges: ['new'],
    specs: { aperture: 'f/4.5-5.6', range: '100-400mm', mount: 'Z Mount', weight: '1355g' },
  },
  {
    id: '45',
    name: 'Canon RF 15-35mm f/2.8L IS USM',
    slug: 'canon-rf-15-35mm',
    description: 'Professional ultra-wide zoom with IS',
    price: 229900,
    images: ['/placeholder.svg?height=800&width=800&text=Canon+15-35mm'],
    category: 'lens',
    brand: 'Canon',
    rating: 4.9,
    reviewCount: 178,
    inStock: true,
    badges: ['hot'],
    specs: { aperture: 'f/2.8', range: '15-35mm', mount: 'RF Mount', weight: '840g' },
  },
  {
    id: '46',
    name: 'Godox V1 Flash',
    slug: 'godox-v1-flash',
    description: 'Round head speedlight with modeling lamp',
    price: 21990,
    images: ['/placeholder.svg?height=800&width=800&text=Godox+V1'],
    category: 'accessory',
    brand: 'Godox',
    rating: 4.7,
    reviewCount: 645,
    inStock: true,
    specs: { power: '76Ws', recycling: '1.5s', battery: '480 shots', weight: '530g' },
  },
  {
    id: '47',
    name: 'Rode VideoMic NTG',
    slug: 'rode-videomic-ntg',
    description: 'Professional shotgun microphone for video',
    price: 24990,
    images: ['/placeholder.svg?height=800&width=800&text=Rode+VideoMic'],
    category: 'accessory',
    brand: 'Rode',
    rating: 4.8,
    reviewCount: 534,
    inStock: true,
    badges: ['hot'],
    specs: { type: 'Shotgun', power: 'Built-in rechargeable', outputs: 'XLR/3.5mm', weight: '162g' },
  },
  {
    id: '48',
    name: 'Lowepro ProTactic BP 450 AW II',
    slug: 'lowepro-protactic-450',
    description: 'Professional camera backpack with all-access design',
    price: 34990,
    images: ['/placeholder.svg?height=800&width=800&text=Lowepro+BP450'],
    category: 'accessory',
    brand: 'Lowepro',
    rating: 4.6,
    reviewCount: 423,
    inStock: true,
    specs: { capacity: '25L', protection: 'All-weather AW cover', laptop: 'Up to 15"', weight: '2.1kg' },
  },
  {
    id: '49',
    name: 'Atomos Ninja V+ 8K HDR Monitor',
    slug: 'atomos-ninja-v-plus',
    description: '5.2" 8K HDR monitor-recorder',
    price: 129900,
    images: ['/placeholder.svg?height=800&width=800&text=Atomos+Ninja'],
    category: 'accessory',
    brand: 'Atomos',
    rating: 4.7,
    reviewCount: 198,
    inStock: true,
    badges: ['new'],
    specs: { display: '5.2" 1920x1080', recording: '8K ProRes RAW', battery: '2+ hours', weight: '360g' },
  },
  {
    id: '50',
    name: 'Think Tank Photo Airport Roller Derby',
    slug: 'thinktank-airport-roller',
    description: 'Rolling camera bag for air travel',
    price: 44990,
    images: ['/placeholder.svg?height=800&width=800&text=ThinkTank+Roller'],
    category: 'accessory',
    brand: 'Think Tank',
    rating: 4.8,
    reviewCount: 267,
    inStock: true,
    specs: { capacity: '35L', wheels: '4-wheel spinner', laptop: 'Up to 15"', weight: '4.3kg' },
  },
  {
    id: '51',
    name: 'Canon EOS R5 Complete Kit',
    slug: 'canon-r5-complete-kit',
    description: 'R5 with 24-70mm & 70-200mm lenses, bag, and accessories',
    price: 599900,
    originalPrice: 749900,
    images: ['/placeholder.svg?height=800&width=800&text=Canon+R5+Kit'],
    category: 'bundle',
    brand: 'Canon',
    rating: 4.9,
    reviewCount: 89,
    inStock: true,
    badges: ['sale', 'hot'],
    specs: { includes: 'R5 Body, RF 24-70 f/2.8, RF 70-200 f/2.8, bag, 2 batteries, 2 cards' },
  },
  {
    id: '52',
    name: 'Sony A7 IV Creator Bundle',
    slug: 'sony-a7iv-creator-bundle',
    description: 'A7 IV with lens, gimbal, and video accessories',
    price: 369900,
    originalPrice: 449900,
    images: ['/placeholder.svg?height=800&width=800&text=Sony+Creator+Kit'],
    category: 'bundle',
    brand: 'Sony',
    rating: 4.8,
    reviewCount: 145,
    inStock: true,
    badges: ['sale'],
    specs: { includes: 'A7 IV, 28-70mm lens, DJI gimbal, mic, memory' },
  },
  {
    id: '53',
    name: 'Nikon Z9 Pro Kit',
    slug: 'nikon-z9-pro-kit',
    description: 'Complete professional setup for sports/wildlife',
    price: 699900,
    images: ['/placeholder.svg?height=800&width=800&text=Nikon+Z9+Kit'],
    category: 'bundle',
    brand: 'Nikon',
    rating: 4.9,
    reviewCount: 67,
    inStock: true,
    badges: ['hot'],
    specs: { includes: 'Z9 Body, Z 24-70 f/2.8, Z 100-400mm, bag, batteries, CFexpress cards' },
  },
  {
    id: '54',
    name: 'Fujifilm X-T5 Travel Kit',
    slug: 'fujifilm-xt5-travel-kit',
    description: 'Perfect travel photography bundle',
    price: 229900,
    originalPrice: 279900,
    images: ['/placeholder.svg?height=800&width=800&text=Fuji+Travel+Kit'],
    category: 'bundle',
    brand: 'Fujifilm',
    rating: 4.7,
    reviewCount: 198,
    inStock: true,
    badges: ['sale'],
    specs: { includes: 'X-T5, XF 16-80mm, bag, tripod, filters, SD cards' },
  },
  {
    id: '55',
    name: 'Beginner Photography Starter Pack',
    slug: 'beginner-starter-pack',
    description: 'Everything you need to start photography',
    price: 89900,
    originalPrice: 119900,
    images: ['/placeholder.svg?height=800&width=800&text=Starter+Pack'],
    category: 'bundle',
    brand: 'Multiple',
    rating: 4.6,
    reviewCount: 567,
    inStock: true,
    badges: ['sale', 'hot'],
    specs: { includes: 'Entry camera, kit lens, bag, tripod, memory, cleaning kit' },
  },
  {
    id: '56',
    name: 'Studio Lighting Bundle',
    slug: 'studio-lighting-bundle',
    description: 'Complete 3-light studio setup',
    price: 79900,
    images: ['/placeholder.svg?height=800&width=800&text=Studio+Lighting'],
    category: 'bundle',
    brand: 'Godox',
    rating: 4.7,
    reviewCount: 334,
    inStock: true,
    specs: { includes: '3x strobes, 3x stands, 3x softboxes, triggers, bag' },
  },
  {
    id: '57',
    name: 'Vlogger Pro Kit',
    slug: 'vlogger-pro-kit',
    description: 'Professional vlogging setup',
    price: 129900,
    originalPrice: 159900,
    images: ['/placeholder.svg?height=800&width=800&text=Vlogger+Kit'],
    category: 'bundle',
    brand: 'Sony',
    rating: 4.8,
    reviewCount: 456,
    inStock: true,
    badges: ['sale', 'new'],
    specs: { includes: 'ZV-E10, 16-50mm, wireless mic, LED light, tripod, gimbal' },
  },
  {
    id: '58',
    name: 'Wildlife Photography Bundle',
    slug: 'wildlife-photography-bundle',
    description: 'Long-range wildlife shooting kit',
    price: 449900,
    images: ['/placeholder.svg?height=800&width=800&text=Wildlife+Kit'],
    category: 'bundle',
    brand: 'Canon',
    rating: 4.9,
    reviewCount: 123,
    inStock: true,
    badges: ['hot'],
    specs: { includes: 'R7 Body, RF 100-500mm, RF 800mm f/11, camouflage bag' },
  },
  {
    id: '59',
    name: 'Portrait Photography Pro Set',
    slug: 'portrait-photography-pro-set',
    description: 'Everything for stunning portraits',
    price: 269900,
    images: ['/placeholder.svg?height=800&width=800&text=Portrait+Kit'],
    category: 'bundle',
    brand: 'Nikon',
    rating: 4.8,
    reviewCount: 234,
    inStock: true,
    specs: { includes: 'Z6 III, Z 85mm f/1.8, Z 35mm f/1.8, flash, reflector' },
  },
  {
    id: '60',
    name: 'Landscape Essentials Bundle',
    slug: 'landscape-essentials-bundle',
    description: 'Complete landscape photography setup',
    price: 199900,
    originalPrice: 249900,
    images: ['/placeholder.svg?height=800&width=800&text=Landscape+Kit'],
    category: 'bundle',
    brand: 'Sony',
    rating: 4.7,
    reviewCount: 298,
    inStock: true,
    badges: ['sale'],
    specs: { includes: 'A7C II, FE 16-35 f/4, carbon tripod, ND filters, bag' },
  },
];
